### ISSUE TITLE
OwlCarousel2 branch disappeared?

### ISSUE THREAD

**Issue by Hellfar** [acrogenesis/owlcarousel-rails#11]
Hi,

As the README indicates, I tried:

```
    gem 'owlcarousel-rails', github: 'acrogenesis/owlcarousel-rails', branch: 'OwlCarousel2'
```

But the branch `OwlCarousel2` seems to not exist anymore?

Thanks in advance.

**Comment by acrogenesis** [comment]
It as merged to master. Use the master branch instead.

**Comment by Hellfar** [comment]
I understand, I thought not be on OwlCarousel2 was my issue then.

I have a problem with the `loop` feature.
I copied the basic example [here](https://owlcarousel2.github.io/OwlCarousel2/demos/basic.html) as:
```
<div class="row border-top">
  <div class="col text-center p-5">
    <h3>Carousel</h3>
    <div class="owl-carousel owl-theme">
      <div class="item"><h4>1</h4></div>
      <div class="item"><h4>2</h4></div>
      <div class="item"><h4>3</h4></div>
      <div class="item"><h4>4</h4></div>
      <div class="item"><h4>5</h4></div>
      <div class="item"><h4>6</h4></div>
      <div class="item"><h4>7</h4></div>
      <div class="item"><h4>8</h4></div>
      <div class="item"><h4>9</h4></div>
      <div class="item"><h4>10</h4></div>
      <div class="item"><h4>11</h4></div>
      <div class="item"><h4>12</h4></div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $('.owl-carousel').owlCarousel({
      loop:true,
      margin:10,
      nav:true,
      responsive:{
          0:{
              items:1
          },
          600:{
              items:3
          },
          1000:{
              items:5
          }
      }
    });
  });
</script>
```

Yet, my carousel isn't looping like in the example.

I checked from the resources I am on `jQuery OwlCarousel v1.3.3` and the same code from a static page (not with rails) is working fine.

I had add `//= require owl.carousel` to my `application.coffee` and `@import "owl.carousel";
@import "owl.theme";` to my `application.scss`.

(Using `bootstrap (4.0.0)`).

Do you have an idea of what would be my problem ?

**Comment by krtschmr** [comment]
We have same issue that the branch is gone.... do you mind rebranching it?

**Comment by acrogenesis** [comment]
OwlCarousel2 is now the current release, so just do `gem 'owlcarousel-rails'` `bundle update`
