### ISSUE TITLE
Uncaught TypeError: $(...).owlCarousel is not a function

### ISSUE THREAD

**Issue by GraphicDesk** [acrogenesis/owlcarousel-rails#8]
Hi,

I followed your instruction but I keep bumping in the error displayed above.

Can you please help ?

**Comment by acrogenesis** [comment]
Did you require `//= require owl.carousel` on your application.js, but it below jquery

**Comment by GraphicDesk** [comment]
Here is my application.js structure

//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require_tree .
//= require owl.carousel

**Comment by GraphicDesk** [comment]
Solved.

I'm working on Spree.. Had to add the dependencies into vendor/spree ....
